
version: '3.10'
services:
  server:
    image: vid-server
    container_name: vid-server
    environment:
      - CHOKIDAR_USEPOLLING=true
    # restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app/server

  client:
    image: vid-client
    container_name: vid-client
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    build: 
      context: ./frontend
      dockerfile: Dockerfile.local
    expose: 
      - 3000
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/client
    depends_on:
      - server
volumes:
  node_modules: